Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  UseCache: false
  TargetRubyVersion: 2.5
  Exclude:
  - 'bin/**/*'
  - 'Rakefile'
  - 'vendor/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'spec/rails_helper.rb'
  -  'spec/spec_helper.rb'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
